from __future__ import annotations


PRIMARY_CATEGORIES = [
    "Bread",
    "Pastries",
    "Cakes",
    "Eggs",
    "Milk",
    "Plant-based milk",
    "Butter",
    "Cheese",
    "Soft cheese and spreads",
    "Yogurt",
    "Cream",
    "Chicken breast",
    "Chicken thighs",
    "Beef",
    "Pork",
    "Lamb",
    "Turkey",
    "Deli meat",
    "Sausages",
    "Bacon",
    "Fish",
    "Seafood",
    "Rice",
    "Pasta",
    "Noodles",
    "Flour",
    "Sugar",
    "Oats",
    "Cereal",
    "Granola",
    "Beans",
    "Lentils",
    "Chickpeas",
    "Nuts",
    "Seeds",
    "Dried fruit",
    "Fruit",
    "Apples",
    "Bananas",
    "Oranges",
    "Lemons and limes",
    "Grapes",
    "Berries",
    "Melons",
    "Stone fruit",
    "Tropical fruit",
    "Avocados",
    "Vegetables",
    "Potatoes",
    "Sweet potatoes",
    "Onions",
    "Garlic",
    "Carrots",
    "Tomatoes",
    "Cucumbers",
    "Lettuce",
    "Spinach",
    "Broccoli",
    "Cauliflower",
    "Peppers",
    "Mushrooms",
    "Zucchini",
    "Eggplant",
    "Cabbage",
    "Leeks",
    "Asparagus",
    "Fresh herbs",
    "Frozen vegetables",
    "Frozen fruit",
    "Canned vegetables",
    "Canned fruit",
    "Canned fish",
    "Canned meat",
    "Soup",
    "Pizza",
    "Prepared meals",
    "Sandwiches",
    "Salads",
    "Sauces",
    "Condiments",
    "Cooking oil",
    "Vinegar",
    "Salt",
    "Spices",
    "Stock",
    "Baking ingredients",
    "Snacks & sweets",
    "Chocolate",
    "Candy",
    "Packaged snacks",
    "Ice cream",
    "Desserts",
    "Gum and mints",
    "Drinks",
    "Coffee for home",
    "Prepared coffee drinks",
    "Tea",
    "Bottled water",
    "Sparkling water",
    "Juice",
    "Smoothies",
    "Soft drinks",
    "Energy drinks",
    "Sports drinks",
    "Beer",
    "Wine",
    "Sparkling wine",
    "Cider",
    "Spirits",
    "Ready-to-drink alcoholic drinks",
    "Non-alcoholic beer and wine",
    "Cigarettes",
    "Rolling tobacco",
    "Vapes",
    "Nicotine pouches",
    "Smoking accessories",
    "Personal care",
    "Shampoo",
    "Conditioner",
    "Body wash",
    "Soap",
    "Toothpaste",
    "Toothbrushes",
    "Deodorant",
    "Skincare",
    "Hair styling products",
    "Razors",
    "Shaving products",
    "Feminine care",
    "Condoms",
    "Household goods",
    "Toilet paper",
    "Paper towels",
    "Tissues",
    "Laundry detergent",
    "Fabric softener",
    "Dish soap",
    "Dishwasher products",
    "Surface cleaner",
    "Bathroom cleaner",
    "Trash bags",
    "Foil and food wrap",
    "Food storage bags",
    "Batteries",
    "Light bulbs",
    "Baby products",
    "Pet food",
    "Pet products",
    "Over-the-counter medicine",
    "Vitamins",
    "First aid products",
]
