services:
  postgres:
    image: postgres:16
    container_name: spending_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spending_app
    ports:
      - "5432:5432"
    volumes:
      - spending_postgres_data:/var/lib/postgresql/data
      - ./ranceipt_db_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  spending_postgres_data: